build:
  image: plugins/drone-git
  commands:
    - true
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ciscocloud/nginx-mantlui
    tag: dev
    when:
      branch: master
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ciscocloud/nginx-mantlui
    tag:
      - $$TAG
      - latest
    when:
      event: tag